In [78]:
#!pip3.9 install -U numpy
#!pip3.9 install --pre -U pycaret --user
# print("PyCaret Installed")

In [2]:
import numpy as np
import pandas as pd

In [3]:
tweets = pd.read_csv("cyberbullying_tweets.csv")
tweets

                                              tweet_text cyberbullying_type
0      In other words #katandandre, your food was cra...  not_cyberbullying
1      Why is #aussietv so white? #MKR #theblock #ImA...  not_cyberbullying
2      @XochitlSuckkks a classy whore? Or more red ve...  not_cyberbullying
3      @Jason_Gio meh. :P  thanks for the heads up, b...  not_cyberbullying
4      @RudhoeEnglish This is an ISIS account pretend...  not_cyberbullying
...                                                  ...                ...
47687  Black ppl aren't expected to do anything, depe...          ethnicity
47688  Turner did not withhold his disappointment. Tu...          ethnicity
47689  I swear to God. This dumb nigger bitch. I have...          ethnicity
47690  Yea fuck you RT @therealexel: IF YOURE A NIGGE...          ethnicity
47691  Bro. U gotta chill RT @CHILLShrammy: Dog FUCK ...          ethnicity

[47692 rows x 2 columns]

In [4]:
tweets["cyberbullying_type"].unique()

array(['not_cyberbullying', 'gender', 'religion', 'other_cyberbullying',
       'age', 'ethnicity'], dtype=object)

In [5]:
tweets20 = tweets.head(20000)

In [6]:
from pycaret.nlp import *
from pycaret.classification import *
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
tf_vectorizer = CountVectorizer(min_df=.015, max_df=.8, max_features=5, ngram_range=[1, 3])

In [8]:
%time features = tf_vectorizer.fit_transform(tweets20['tweet_text'])
features

CPU times: user 3.42 s, sys: 133 ms, total: 3.55 s
Wall time: 3.59 s

<20000x5 sparse matrix of type '<class 'numpy.int64'>'
	with 29717 stored elements in Compressed Sparse Row format>

In [9]:
features_df = pd.DataFrame(features.toarray(), columns=tf_vectorizer.get_feature_names())
features_df

       and  is  the  to  you
0        0   0    0   0    0
1        0   1    0   0    0
2        0   0    0   0    0
3        0   0    1   0    0
4        0   2    0   1    0
...    ...  ..  ...  ..  ...
19995    1   0    0   1    0
19996    0   0    1   0    0
19997    0   2    2   0    2
19998    0   0    1   0    1
19999    0   0    1   0    1

[20000 rows x 5 columns]

In [10]:
df = pd.concat([features_df,tweets20['cyberbullying_type']],axis=1)
df

       and  is  the  to  you cyberbullying_type
0        0   0    0   0    0  not_cyberbullying
1        0   1    0   0    0  not_cyberbullying
2        0   0    0   0    0  not_cyberbullying
3        0   0    1   0    0  not_cyberbullying
4        0   2    0   1    0  not_cyberbullying
...    ...  ..  ...  ..  ...                ...
19995    1   0    0   1    0           religion
19996    0   0    1   0    0           religion
19997    0   2    2   0    2           religion
19998    0   0    1   0    1           religion
19999    0   0    1   0    1           religion

[20000 rows x 6 columns]

In [11]:
#Shuffle your dataset 
shuffle_df = df.sample(frac=1)

# Define a size for your train set
# 90% training, 10% testing
train_size = int(0.9 * len(df))

# Split your dataset 
train_df = shuffle_df[:train_size]
test_df  = shuffle_df[train_size:]

In [12]:
numerical_features = list(features_df.columns)
%time temp = setup(data = train_df, target = 'cyberbullying_type',numeric_features=numerical_features)

CPU times: user 1.32 s, sys: 72.1 ms, total: 1.39 s
Wall time: 1.82 s

In [13]:
%time lightgbm = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

CPU times: user 2.09 s, sys: 236 ms, total: 2.33 s
Wall time: 10.5 s

In [14]:
%time tuned_lightgbm = tune_model(lightgbm)

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits
CPU times: user 6.28 s, sys: 203 ms, total: 6.48 s
Wall time: 33.2 s

In [16]:
#evaluate model
predict_model(tuned_lightgbm)

,and,is,the,to,you,cyberbullying_type,prediction_label,prediction_score
12599,2.0,1.0,1.0,1.0,1.0,religion,religion,0.5959
12600,0.0,0.0,0.0,0.0,1.0,gender,not_cyberbullying,0.4273
12601,0.0,0.0,0.0,0.0,0.0,not_cyberbullying,not_cyberbullying,0.5634
12602,0.0,1.0,0.0,2.0,0.0,religion,not_cyberbullying,0.3799
12603,0.0,0.0,2.0,0.0,2.0,religion,religion,0.5099
...,...,...,...,...,...,...,...,...
17995,0.0,2.0,3.0,1.0,0.0,gender,religion,0.4062
17996,0.0,0.0,0.0,0.0,0.0,religion,not_cyberbullying,0.5634
17997,0.0,0.0,0.0,0.0,0.0,not_cyberbullying,not_cyberbullying,0.5634
17998,1.0,0.0,0.0,3.0,2.0,gender,religion,0.5178
17999,0.0,0.0,0.0,0.0,0.0,not_cyberbullying,not_cyberbullying,0.5634

In [17]:
#evaluate model
predict_model(tuned_lightgbm,data=test_df)

,and,is,the,to,you,cyberbullying_type,prediction_label,prediction_score
0,0.0,0.0,2.0,0.0,0.0,not_cyberbullying,not_cyberbullying,0.4382
1,1.0,0.0,1.0,1.0,0.0,not_cyberbullying,gender,0.4665
2,0.0,2.0,0.0,0.0,0.0,religion,gender,0.4643
3,0.0,0.0,1.0,1.0,0.0,not_cyberbullying,not_cyberbullying,0.4525
4,1.0,0.0,1.0,0.0,0.0,gender,gender,0.4726
...,...,...,...,...,...,...,...,...
1995,1.0,0.0,1.0,0.0,0.0,gender,gender,0.4726
1996,0.0,0.0,0.0,1.0,1.0,religion,not_cyberbullying,0.4209
1997,1.0,1.0,1.0,0.0,0.0,not_cyberbullying,gender,0.4614
1998,1.0,1.0,0.0,0.0,0.0,not_cyberbullying,gender,0.5186
1999,1.0,0.0,0.0,2.0,1.0,religion,religion,0.4354

In [18]:
compare_models()

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=4866, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)